### ISSUE TITLE
アセットを入れ替える

### ISSUE THREAD

**Issue by lirlia** [recursion-team-v/bomb#221]
- キャラ
- 背景
- アイテム
- 爆弾

**Comment by lirlia** [comment]
# コンセプト

- ファミコンぽいか or 今風か -> ファミコンぽい
- ファミコン or スーファミ -> スーファミ

![image](https://user-images.githubusercontent.com/10017674/213061357-ea3aec73-21cd-4fce-ac49-fd15d6542a1b.png)


<img width="932" alt="image" src="https://user-images.githubusercontent.com/10017674/213061695-7c655991-cb90-4737-96c4-78569f63c10d.png">

<img width="870" alt="image" src="https://user-images.githubusercontent.com/10017674/213062027-fffab73b-6977-4ffd-b057-ed1845343b9a.png">

**Comment by satojin219** [comment]
https://www.bannerkoubou.com/photoeditor/change_color/
