### ISSUE TITLE
ブロック生成方法の修正（プレイヤーの周りはあける）

### ISSUE THREAD

**Issue by lirlia** [recursion-team-v/bomb#42]
<img width="278" alt="image" src="https://user-images.githubusercontent.com/10017674/209454873-5a29ee7f-8196-4e86-a1fe-ceba96deb8ae.png">

こういう状況があるので、少なくとも自分の周辺1 or 2 マスを必ず空けたいです

<img width="770" alt="image" src="https://user-images.githubusercontent.com/10017674/209454888-73f8ee45-9645-42e7-8ecb-3667a15aef2d.png">

_Originally posted by @lirlia in https://github.com/recursion-team-v/bomb/issues/40#issuecomment-1364610439_

**Comment by hiroto0222** [comment]
#85 で fix
