### ISSUE TITLE
Game：爆発に当たり判定を付与

### ISSUE THREAD

**Issue by satojin219** [recursion-team-v/bomb#51]

**Comment by satojin219** [comment]
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/81739310/209616689-41225096-1145-4a62-86d8-64581dfcc506.gif)
`const b1 = this.scene.matter.add.sprite(x + 52, y, 'explosion', ).play('tip_explode');
        b1.setData('objectType', ObjectTypes.BLAST);
        group.add(b1);`
matter使ってみましたが、当たり判定が十字になるのではなく、枠が少し広がるだけでした、、
一回クラスで作ってみてどうなるか試してみようかな～と思います

**Comment by satojin219** [comment]
クラスにする前にgroup外したらどうなるか見てみますか

**Comment by hiroto0222** [comment]
> matter使ってみましたが、当たり判定が十字になるのではなく、枠が少し広がるだけでした、、 一回クラスで作ってみてどうなるか試してみようかな～と思います

見た感じ中心の爆風だけに box が作られてますね。
bomb_horizontal_explosion、bomb_horizontal_end_explosion にも同じように this.scene.matter.add.sprite されてますか？

**Comment by satojin219** [comment]
完全に自分のミスでしたね、、matter付与したつもりがついていませんでしたorz
ちゃんとつけたら動くようになりました。今度は５つの爆発が反発しあうようになっているので、そこを修正します

**Comment by hiroto0222** [comment]
> 完全に自分のミスでしたね、、matter付与したつもりがついていませんでしたorz ちゃんとつけたら動くようになりました。今度は５つの爆発が反発しあうようになっているので、そこを修正します

sprite の設定として ```isSensor: true, isStatic: true```（Item も同じ）を使えば反発しなくなると思います。

https://photonstorm.github.io/phaser3-docs/Phaser.Physics.Matter.Components.Sensor.html
> Set the body belonging to this Game Object to be a sensor. Sensors trigger collision events, but don't react with colliding body physically.
